### PR TITLE
Add openai model option

### PR DESCRIPTION
**Pull request by nikitaservais**
Add the option to choose OpenAI model in the settings, specifically for gpt-4

### CODE REVIEW

**Comment by nikitaservais** [comment]
I used gitmoji in the prompt for AI-commit to generate commit messages

**Comment by Blarc** [comment]
Hey @nikitaservais , thanks for making this PR :+1: . Since all these commits are releated to one feature, can you please squash them into one and write a commit message using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification. :pray:

**Comment by Blarc** [comment]
I have added code for fetching OpenAI model ids from OpenAI API instead of hardcoding them. There is one more thing. I check if prompt is too big in [isPromptTooLarge](https://github.com/Blarc/ai-commits-intellij-plugin/blob/main/src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitAction.kt#L109). The hardcoded value 4000 is relevant for `gpt-3.5-turbo` but not for other models. The encoding type for computing the number of tokens probably isn't correct either. Need to check if we can get these model properties somehow. The other solution would be to just not check and let the API do the validation.

**Comment by Blarc** [comment]
I have removed prompt length checking. It is now validated by the OpenAI API and results in an error notification if the diff is too big:
image

**Pull request merged**
